### ISSUE TITLE
in latest image upip doesn't work anymore

### ISSUE THREAD

**Issue by fruch** [mrooding/micropython-docker#2]
```
>>> upip.install('micropython-os')
Installing to: /scripts/
Queue: ['micropython-os']
ssl_handshake_status: -70
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "upip.py", line 213, in install
  File "upip.py", line 203, in install
  File "upip.py", line 160, in install_pkg
  File "upip.py", line 147, in get_pkg_metadata
  File "upip.py", line 120, in url_open
OSError: [Errno 5] EIO
```

**Comment by fruch** [comment]
Can you point to the newer more upto date image from this repo ?
https://github.com/mitchins/docker-micropython-linux
